Add support for external id auth hash token
OneSignal/OneSignal-Cordova-SDK pull request #678
Opened 2020-12-03 04:55 UTC by Jeasmine

* Add authentication support for external Id
* Update callbacks support

2020-12-03 05:06 UTC, jkasten2 requested changes

2020-12-03 05:06 UTC, jkasten2 commented on www/OneSignal.js
> +OneSignal.prototype.setExternalUserIdWithAuthToken = function(externalId, authHashToken, externalUserIdCallback) {
For react native we made the authhash optional instead of a new method name.

Since Javascript does not support method overloading via defining the same function with different params we have to detected the type via `typeof`. See how this was implemented here:
https://github.com/OneSignal/react-native-onesignal/pull/1097/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R441-R446

2020-12-05 00:30 UTC, jkasten2 approved these changes

2020-12-05 02:30 UTC, jkasten2 requested changes

2020-12-05 02:30 UTC, jkasten2 commented on www/OneSignal.js
> +    cordova.exec(externalUserIdCallback, function() {}, "OneSignalPush", "setExternalUserId", [externalId, varArg1]);
`externalUserIdCallback` isn't defined which results in this error when running on a device.

Getting error here `file:///android_asset/www/plugins/onesignal-cordova-plugin/www/OneSignal.js: Line 302 : Uncaught ReferenceError: externalUserIdCallback is not defined`

2020-12-05 02:30 UTC, jkasten2 commented on www/OneSignal.js
> +OneSignal.prototype.setExternalUserId = function(externalId, varArg1, varArg2) {
This could be cleaner by assign `varArg1` and `varArg1` to local variables then only have a single call to `cordova.exec`.

2020-12-05 03:02 UTC, jkasten2 commented on www/OneSignal.js
> +    cordova.exec(externalUserIdCallback, function() {}, "OneSignalPush", "setExternalUserId", [externalId, varArg1]);
Fixup in PR: https://github.com/OneSignal/OneSignal-Cordova-SDK/pull/680

2020-12-05 03:02 UTC, jkasten2 commented on www/OneSignal.js
> +OneSignal.prototype.setExternalUserId = function(externalId, varArg1, varArg2) {
Fixup in PR: https://github.com/OneSignal/OneSignal-Cordova-SDK/pull/680

2020-12-07 17:03 UTC, Jeasmine commented
Was able to test on Android 10, working correctly.

Not able to test on iOS:
Unable to load Platform API from /Users/jnahui/Desktop/Proyects.nosync/OneSignal-Cordova-Example/platforms/ios/cordova/Api.js:
Cannot find module 'unorm'

2020-12-07 18:21 UTC, jkasten2 commented
@Jeasmine Weird on the iOS `unorm` issue . I was using iOS 14.2, with Cordova CLI 9.0.0, and cordova-ios@5.1.1 and confirmed things are working. And just created a basic project with ` cordova create`.

2020-12-07 18:24 UTC, jkasten2 approved these changes

2020-12-07 21:59 UTC, merged