WIP - Major release 3.0.0
OneSignal/OneSignal-Cordova-SDK pull request #695
Opened 2021-03-17 16:30 UTC by Jeasmine

2021-04-07 10:12 UTC, jkasten2 requested changes
I took high level pass over this PR as well as dove into some specific areas such as `plugin.xml` but didn't do a deep dive on all code. I recommend we review the interface we have for react-native-onesignal and make sure it matches as close as we can where it make sense to do so.
https://github.com/OneSignal/react-native-onesignal/blob/master/src/index.d.ts

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-:-MXfo4TO0LG0bgr2MioZ:byr2ey6)* status: 0 of 9 files reviewed, 12 unresolved discussions (waiting on @Jeasmine)

___
*[plugin.xml, line 29 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfiQIJ65XBn3jZ6ITX:-MXfiQIJ65XBn3jZ6ITY:b-jz7n3s) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/plugin.xml#L29)):*
> ```XML
> 
>   <platform name="android">
>     <framework src="com.onesignal:OneSignal:4.2.0" />
> ```

Update to 4.3.0
___
*[plugin.xml, line 38 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfmkku3NBuoobBCW8k:-MXfmkku3NBuoobBCW8l:b-fvisyf) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/plugin.xml#L38)):*
> ```XML
>     </config-file>
> 
>     <!-- PhoneGap Build (PGB) does not have a amazon build target so it include the required manifest entries in all Android builds. -->
> ```

This amazon fire section is being added to every Android app. Thinking this would be a good time to remove this as part of the major release. We will just need to instruction developers then to add these `config-file` entry as part of our Amazon setup guide for Cordova then.

Long term thinking we could make a cordova plugin calling something like onesignal-cordova-plugin-fireos that just adds these for them however.
___
*[plugin.xml, line 76 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfnihj5hx7BuzQawMT:-MXfnihj5hx7BuzQawMU:b7a99zc) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/plugin.xml#L76)):*
> ```XML
>     </config-file>
> 
>     <framework src="SystemConfiguration.framework" />
> ```

We should be able to remove this. All the dependencies should be coming in from cocoapods.
___
*[plugin.xml, line 91 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfiT5v2tICf4Q6VmFa:-MXfiT5v2tICf4Q6VmFb:b-jzreyg) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/plugin.xml#L91)):*
> ```XML
>     </config-file>
> 
>     <framework src="OneSignal" type="podspec" spec="3.2.3" />
> ```

Update to 3.4.0
___
*[plugin.xml, line 98 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXflX3FAB7pB2b8uCNA:-MXflX3FAB7pB2b8uCNB:b-elakp2) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/plugin.xml#L98)):*
> ```XML
> 
>   <!-- Windows Phone 8.1 -->
>   <platform name="windows">
> ```

Let's remove the Windows Phone support as part of the major release.
___
*[src/android/com/plugin/gcm/OneSignalController.java, line 1 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfiZhyAzmviumI4QMb:-MXfiZhzDNa9VrCMREWM:b-nb26gz) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/src/android/com/plugin/gcm/OneSignalController.java#L1)):*
> ```Java
> package com.plugin.gcm;
> ```

This would be a good time to change to a better namespace. What do you think of `com.onesignal.cordova`?
___
*[src/android/com/plugin/gcm/OneSignalPush.java, line 360 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfkAYXEKHpgiyf1K4i:-MXfkAYXEKHpgiyf1K4j:bqltg62) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/src/android/com/plugin/gcm/OneSignalPush.java#L360)):*
> ```Java
>     public void notificationWillShowInForeground(OSNotificationReceivedEvent notificationReceivedEvent) {
>       try {
>         if (jsNotificationInForegroundCallBack == null) {
> ```

I don't think this could ever be `null` correct?
___
*[www/OneSignal.js, line 47 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfkiRJ5mIdEnX1s2Qf:-MXfkiRJ5mIdEnX1s2Qg:b-px4ewn) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/www/OneSignal.js#L47)):*
> ```JavaScript
> 
> // You must call init before any other OneSignal function.
> OneSignal.prototype.startInit = function(appId) {
> ```

`startInit` should be replaced with `setAppId`. 
___
*[www/OneSignal.js, line 49 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfkneBE0l_ODGNxFeZ:-MXfkneBE0l_ODGNxFe_:bveue5y) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/www/OneSignal.js#L49)):*
> ```JavaScript
> OneSignal.prototype.startInit = function(appId) {
>     OneSignal._appID = appId;
>     return this;
> ```

Remove `return this`, we don't want to support dot chaining any more.
___
*[www/OneSignal.js, line 54 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfkpK587D77DycJCcR:-MXfkpK587D77DycJCcS:bveue5y) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/www/OneSignal.js#L54)):*
> ```JavaScript
> OneSignal.prototype.handleNotificationWillShowInForeground = function(handleNotificationWillShowInForegroundCallback) {
>     OneSignal._notificationWillShowInForegroundDelegate = handleNotificationWillShowInForegroundCallback;
>     return this;
> ```

Remove `return this`, we don't want to support dot chaining any more.
___
*[www/OneSignal.js, line 59 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfkuDF5VviWYLHEwWX:-MXfkuDF5VviWYLHEwWY:bveue5y) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/www/OneSignal.js#L59)):*
> ```JavaScript
> OneSignal.prototype.handleNotificationOpened = function(handleNotificationOpenedCallback) {
>     OneSignal._notificationOpenedDelegate = handleNotificationOpenedCallback;
>     return this;
> ```

Remove `return this`, we don't want to support dot chaining any more.
___
*[www/OneSignal.js, line 64 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfkury4jQnMrMBtZNn:-MXfkury4jQnMrMBtZNo:bveue5y) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/www/OneSignal.js#L64)):*
> ```JavaScript
> OneSignal.prototype.handleInAppMessageClicked = function(handler) {
>     OneSignal._inAppMessageClickDelegate = handler;
>     return this;
> ```

Remove `return this`, we don't want to support dot chaining any more.


<!-- Sent from Reviewable.io -->

2021-04-19 16:53 UTC, rgomezp commented
___
*[src/android/com/onesignal/cordova/OneSignalController.java, line 23 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYf22oGBvlwzMhuCHMx:-MYf22oH4u9E4e-2ltsA:b-w1u3so) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/src/android/com/onesignal/cordova/OneSignalController.java#L23)):*
> ```Java
>     OSDeviceState deviceState = OneSignal.getDeviceState();
>     if (deviceState != null)
>       CallbackHelper.callbackSuccess(callbackContext, deviceState.toJSONObject());
> ```

should have brackets. e.g: 

```
if (true) {
   // do something
}
```


<!-- Sent from Reviewable.io -->

2021-04-19 17:00 UTC, rgomezp commented
___
*[src/android/com/onesignal/cordova/OneSignalInAppMessagingController.java, line 19 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYf3glw1ut0kEX39BmD:-MYf3glw1ut0kEX39BmE:b-jxpbz4) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/src/android/com/onesignal/cordova/OneSignalInAppMessagingController.java#L19)):*
> ```Java
> public class OneSignalInAppMessagingController {
> 
>     // This is to prevent an issue where if two Javascript calls are made to OneSignal expecting a callback then only one would fire.
> ```

Added unnecessary 4-space tabs


<!-- Sent from Reviewable.io -->

2021-04-19 17:30 UTC, rgomezp commented on src/android/com/plugin/gcm/OneSignalController.java
>  }
Newline

2021-04-19 18:20 UTC, rgomezp requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695)* status: 0 of 11 files reviewed, 20 unresolved discussions (waiting on @Jeasmine)

___
*[www/OneSignal.js, line 128 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYfFgQ752jiykEh-J5-:-MYfFgQ752jiykEh-J50:b-7s4sqq) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/www/OneSignal.js#L128)):*
> ```JavaScript
> 
> OneSignal.prototype.sendTag = function(key, value) {
>     var jsonKeyValue = {};
> ```

const
___
*[www/OneSignal.js, line 452 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYfHFdf9q2o-Et_AeTK:-MYfHFdf9q2o-Et_AeTL:btonum6) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/www/OneSignal.js#L452)):*
> ```JavaScript
>         /// urgent the notification is. A higher priority
>         /// means the notification will be delivered faster.
>         /// Default = 10.
> ```

I'm not sure this is right. I believe priority goes from -2 - 2

See: https://developer.android.com/reference/androidx/core/app/NotificationCompat#PRIORITY_DEFAULT
___
*[www/OneSignal.js, line 453 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYfHVbA24Jq_zEX_voT:-MYfHVbA24Jq_zEX_voU:b-1jfisj) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/www/OneSignal.js#L453)):*
> ```JavaScript
>         /// means the notification will be delivered faster.
>         /// Default = 10.
>         if (receivedEvent.priority) {
> ```

What if the priority value is zero? We should instead check for undefined

Think about other receivedEvent values that could be zero or empty string that would cause the conditional to not work as intended
___
*[www/OneSignal.js, line 708 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYfLS7_Btq3p6I0h-8Q:-MYfLS7_Btq3p6I0h-8R:b2ngme4) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/www/OneSignal.js#L708)):*
> ```JavaScript
>         }
> 
>         if (json.notificationPermissionStatus != null) {
> ```

!==
___
*[www/OneSignal.js, line 722 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYfLs-O2kZoW-7V7xHK:-MYfLs-O2kZoW-7V7xHL:b4ssagz) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/www/OneSignal.js#L722)):*
> ```JavaScript
> }
> 
> class OSPermissionState {
> ```

!== instead of !=
___
*[src/android/com/onesignal/cordova/OneSignalController.java, line 255 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYfEHWx4aNzkXuYZq_O:-MYfEHWx4aNzkXuYZq_P:bcl97k1) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/src/android/com/onesignal/cordova/OneSignalController.java#L255)):*
> ```Java
>   public static boolean isLocationShared(CallbackContext callbackContext) {
>     // doesn't apply to Android
>     CallbackHelper.callbackSuccessBoolean(callbackContext, false);
> ```

why doesn't it apply to Android? add more info in comment


<!-- Sent from Reviewable.io -->

2021-04-20 18:11 UTC, Jeasmine reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695)* status: 0 of 15 files reviewed, 20 unresolved discussions (waiting on @Jeasmine, @jkasten2, and @rgomezp)

___
*[plugin.xml, line 29 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfiQIJ65XBn3jZ6ITX:-MYkSWDn3cbUtRNT0bpN:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/plugin.xml#L29)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Update to 4.3.0
</blockquote></details>

Done.
___
*[plugin.xml, line 38 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfmkku3NBuoobBCW8k:-MYkSXFu62nRu3a-_c98:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/plugin.xml#L38)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This amazon fire section is being added to every Android app. Thinking this would be a good time to remove this as part of the major release. We will just need to instruction developers then to add these `config-file` entry as part of our Amazon setup guide for Cordova then.

Long term thinking we could make a cordova plugin calling something like onesignal-cordova-plugin-fireos that just adds these for them however.
</blockquote></details>

Done.
___
*[plugin.xml, line 76 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfnihj5hx7BuzQawMT:-MYkSXwm3GH6nBQOsUQD:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/plugin.xml#L76)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

We should be able to remove this. All the dependencies should be coming in from cocoapods.
</blockquote></details>

Done.
___
*[plugin.xml, line 91 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfiT5v2tICf4Q6VmFa:-MYkSYQj5nT4R3OrHbTu:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/plugin.xml#L91)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Update to 3.4.0
</blockquote></details>

Done.
___
*[plugin.xml, line 98 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXflX3FAB7pB2b8uCNA:-MYkSYlV-DyoXLgRAM0k:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/plugin.xml#L98)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Let's remove the Windows Phone support as part of the major release.
</blockquote></details>

Done.
___
*[www/OneSignal.js, line 47 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfkiRJ5mIdEnX1s2Qf:-MYkTPEzDYQJgtH3BNh8:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/www/OneSignal.js#L47)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

`startInit` should be replaced with `setAppId`. 
</blockquote></details>

Done.
___
*[www/OneSignal.js, line 49 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfkneBE0l_ODGNxFeZ:-MYkTPXy5glLH1EsZDtg:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/www/OneSignal.js#L49)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Remove `return this`, we don't want to support dot chaining any more.
</blockquote></details>

Done.
___
*[www/OneSignal.js, line 54 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfkpK587D77DycJCcR:-MYkTPui3ZggvzQwolVf:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/www/OneSignal.js#L54)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Remove `return this`, we don't want to support dot chaining any more.
</blockquote></details>

Done.
___
*[www/OneSignal.js, line 59 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfkuDF5VviWYLHEwWX:-MYkTQNFEv_XyNHO1YQI:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/www/OneSignal.js#L59)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Remove `return this`, we don't want to support dot chaining any more.
</blockquote></details>

Done.
___
*[www/OneSignal.js, line 64 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfkury4jQnMrMBtZNn:-MYkTQj7DVdVjarQS845:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/www/OneSignal.js#L64)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Remove `return this`, we don't want to support dot chaining any more.
</blockquote></details>

Done.
___
*[www/OneSignal.js, line 128 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYfFgQ752jiykEh-J5-:-MYkTVE5DXtmY4Vq68yd:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/www/OneSignal.js#L128)):*
<details><summary><i>Previously, rgomezp (Rodrigo Gomez Palacio) wrote…</i></summary><blockquote>

const
</blockquote></details>

Done.
___
*[src/android/com/onesignal/cordova/OneSignalController.java, line 23 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYf22oGBvlwzMhuCHMx:-MYkS_BL5u1Q_lXFan20:b-esi1i5) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/src/android/com/onesignal/cordova/OneSignalController.java#L23)):*
<details><summary><i>Previously, rgomezp (Rodrigo Gomez Palacio) wrote…</i></summary><blockquote>

should have brackets. e.g: 

```
if (true) {
   // do something
}
```
</blockquote></details>

Actually, on Java, we use the following convection: if the if statement is one-liner then go without brackets
___
*[src/android/com/onesignal/cordova/OneSignalController.java, line 255 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYfEHWx4aNzkXuYZq_O:-MYkT2w54jQbOcFh2hu5:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/src/android/com/onesignal/cordova/OneSignalController.java#L255)):*
<details><summary><i>Previously, rgomezp (Rodrigo Gomez Palacio) wrote…</i></summary><blockquote>

why doesn't it apply to Android? add more info in comment
</blockquote></details>

Done.
___
*[src/android/com/onesignal/cordova/OneSignalInAppMessagingController.java, line 19 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYf3glw1ut0kEX39BmD:-MYkTDV26WWt2sK9eVr0:b-ycakzz) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/src/android/com/onesignal/cordova/OneSignalInAppMessagingController.java#L19)):*
> ```
> is is to prevent an issue where if two Javascript calls are made to OneSignal expecting a callback then only one would fire.
> ```
Do you mean to re-indent with 2 scapes all the file?
___
*[src/android/com/plugin/gcm/OneSignalController.java, line 1 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfiZhyAzmviumI4QMb:-MYkSZPsB142t9KcAz-6:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/src/android/com/plugin/gcm/OneSignalController.java#L1)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This would be a good time to change to a better namespace. What do you think of `com.onesi [...]

2021-04-20 18:54 UTC, Jeasmine reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695)* status: 0 of 15 files reviewed, 20 unresolved discussions (waiting on @jkasten2 and @rgomezp)

___
*[www/OneSignal.js, line 452 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYfHFdf9q2o-Et_AeTK:-MYkcXFiCr0kUelgIlm6:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/www/OneSignal.js#L452)):*
<details><summary><i>Previously, rgomezp (Rodrigo Gomez Palacio) wrote…</i></summary><blockquote>

I'm not sure this is right. I believe priority goes from -2 - 2

See: https://developer.android.com/reference/androidx/core/app/NotificationCompat#PRIORITY_DEFAULT
</blockquote></details>

Done.
___
*[www/OneSignal.js, line 453 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYfHVbA24Jq_zEX_voT:-MYkcXc-CIxkB0fns0z_:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/www/OneSignal.js#L453)):*
<details><summary><i>Previously, rgomezp (Rodrigo Gomez Palacio) wrote…</i></summary><blockquote>

What if the priority value is zero? We should instead check for undefined

Think about other receivedEvent values that could be zero or empty string that would cause the conditional to not work as intended
</blockquote></details>

Done.
___
*[www/OneSignal.js, line 708 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYfLS7_Btq3p6I0h-8Q:-MYkUCEd9Lsqh2xZRf7E:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/www/OneSignal.js#L708)):*
<details><summary><i>Previously, rgomezp (Rodrigo Gomez Palacio) wrote…</i></summary><blockquote>

!==
</blockquote></details>

Done.
___
*[www/OneSignal.js, line 722 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYfLs-O2kZoW-7V7xHK:-MYkUC_R-SuupRpGPHoj:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/www/OneSignal.js#L722)):*
<details><summary><i>Previously, rgomezp (Rodrigo Gomez Palacio) wrote…</i></summary><blockquote>

!== instead of !=
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-20 21:01 UTC, rgomezp commented
___
*[src/android/com/onesignal/cordova/OneSignalInAppMessagingController.java, line 19 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYf3glw1ut0kEX39BmD:-MYl4YYP6ZFgMxwWYSX4:blfm7tm) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/src/android/com/onesignal/cordova/OneSignalInAppMessagingController.java#L19)):*
<details><summary><i>Previously, Jeasmine (JNahui) wrote…</i></summary><blockquote>

> ```
> is is to prevent an issue where if two Javascript calls are made to OneSignal expecting a callback then only one would fire.
> ```
Do you mean to re-indent with 2 scapes all the file?
</blockquote></details>

yes. shouldn't it be 2 spaces?


<!-- Sent from Reviewable.io -->

2021-04-20 21:03 UTC, Jeasmine reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695)* status: 0 of 15 files reviewed, 20 unresolved discussions (waiting on @jkasten2 and @rgomezp)

___
*[src/android/com/onesignal/cordova/OneSignalInAppMessagingController.java, line 19 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYf3glw1ut0kEX39BmD:-MYl4szA8VVpNOic-hcz:bdhu5l2) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/src/android/com/onesignal/cordova/OneSignalInAppMessagingController.java#L19)):*
<details><summary><i>Previously, rgomezp (Rodrigo Gomez Palacio) wrote…</i></summary><blockquote>

yes. shouldn't it be 2 spaces?
</blockquote></details>

Actually, by default, Android Studio reformat code has 4 spaces by default, so this is something just to be defined by convention. Currently, we are using 4 at OneSignal Android SDK


<!-- Sent from Reviewable.io -->

2021-04-23 22:10 UTC, jkasten2 requested changes
> Reviewed 1 of 9 files at r1, 5 of 10 files at r2, 2 of 6 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695)* status: 12 of 15 files reviewed, 17 unresolved discussions (waiting on @Jeasmine, @jkasten2, and @rgomezp)

___
*[plugin.xml, line 76 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfnihj5hx7BuzQawMT:-MZ-i90P8Yyo-oDPBBvH:b-6st1mp) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/plugin.xml#L76)):*
<details><summary><i>Previously, Jeasmine (JNahui) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like the wrong section was removed.
We want to keep ` <config-file target="*-Info.plist" parent="UIBackgroundModes">` but remove `<framework src="SystemConfiguration.framework" />`.
___
*[plugin.xml, line 74 at r4](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MZ-jCOg-gobx8XcD_re:-MZ-jCOg-gobx8XcD_rf:b-7dtlb1) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/a5a3a29b1acec2ad1a60de2dd23cf9fd17305165/plugin.xml#L74)):*
> ```XML
> 
>     <js-module src="www/NotificationReceived.js" name="NotificationReceived" />
>     <js-module src="www/NotificationOpened.js" name="NotificationOpened" />
> ```

Looks like these `js-module` tags are repeated for iOS and Android. Can we move them outside of the `<platforms>` so they are only defined once?
It looks like this is possible according to Cordova's docs:
https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#js-module
___
*[src/ios/OneSignalPush.m, line 238 at r4](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MZ-kyJHAdO2kZax0JhY:-MZ-kyJHAdO2kZax0JhZ:b-j8oek5) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/a5a3a29b1acec2ad1a60de2dd23cf9fd17305165/src/ios/OneSignalPush.m#L238)):*
> ```objc
> 
> - (void)addSubscriptionObserver:(CDVInvokedUrlCommand*)command {
>     bool first = subscriptionObserverCallbackId  == nil;
> ```

nit, extra space after `subscriptionObserverCallbackId`.
___
*[src/android/com/onesignal/cordova/OneSignalInAppMessagingController.java, line 19 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MYf3glw1ut0kEX39BmD:-MZ-jvhT8XCROQQNdQ9Q:b-2cs9hc) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/5d1c68b3240f8fea59ec8ed7d5026cb16df274e0/src/android/com/onesignal/cordova/OneSignalInAppMessagingController.java#L19)):*
<details><summary><i>Previously, Jeasmine (JNahui) wrote…</i></summary><blockquote>

Actually, by default, Android Studio reformat code has 4 spaces by default, so this is something just to be defined by convention. Currently, we are using 4 at OneSignal Android SDK
</blockquote></details>

We have been using 2 spaces for .js files but 4 spaces for java files. These seem to be defaults for these languages so thinking we should continue with these spacing rules.
___
*[src/android/com/plugin/gcm/OneSignalController.java, line 1 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfiZhyAzmviumI4QMb:-MZ-jZFq7Kgv6xIwHujl:b-ra0xjj) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/src/android/com/plugin/gcm/OneSignalController.java#L1)):*
<details><summary><i>Previously, Jeasmine (JNahui) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:partying_face: 


<!-- Sent from Reviewable.io -->

2021-04-26 15:31 UTC, Jeasmine reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695)* status: 12 of 15 files reviewed, 17 unresolved discussions (waiting on @Jeasmine, @jkasten2, and @rgomezp)

___
*[plugin.xml, line 76 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MXfnihj5hx7BuzQawMT:-MZDhBBk20NrO0cN9m_u:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/154f0c9ca7f5ff0ea15eada029f91b2acf971081/plugin.xml#L76)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Looks like the wrong section was removed.
We want to keep ` <config-file target="*-Info.plist" parent="UIBackgroundModes">` but remove `<framework src="SystemConfiguration.framework" />`.
</blockquote></details>

Done.
___
*[plugin.xml, line 74 at r4](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-MZ-jCOg-gobx8XcD_re:-MZDnIZqEXpfb-zRxqOa:b-896fix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/a5a3a29b1acec2ad1a60de2dd23cf9fd17305165/plugin.xml#L74)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Looks like these `js-module` tags are repeated for iOS and Android. Can we move them outside of the `<platforms>` so they are only defined once?
It looks like this is possible according to Cordova's docs:
https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#js-module

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-27 21:54 UTC, jkasten2 approved these changes
> Reviewed 2 of 10 files at r2, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695)* status: all files reviewed, 8 unresolved discussions (waiting on @rgomezp)



<!-- Sent from Reviewable.io -->

2021-04-27 21:56 UTC, jkasten2 approved these changes
PR looks good to me! Needs version set to 3.0.0-beta1 in `package.json` and `plugin.xml` before we push to NPMJS

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/695#-:-MZKK1qRA8BhF6NHT1wP:bdq66rd)* status: all files reviewed, 8 unresolved discussions (waiting on @rgomezp)



<!-- Sent from Reviewable.io -->

2021-04-28 18:32 UTC, rgomezp commented on www/NotificationOpened.js
> +module.exports = OSNotificationOpenedResult;
newline

2021-04-28 18:32 UTC, rgomezp commented on src/android/com/onesignal/cordova/OneSignalController.java
>  }
newline

2021-04-28 18:34 UTC, rgomezp commented on www/Subscription.js
> +};
newline

2021-08-06 20:28 UTC, merged