Fix TypeScript types
OneSignal/OneSignal-Cordova-SDK pull request #762
Opened 2021-12-21 17:52 UTC by nunoarruda

Fixes #761 and #726

2022-01-10 14:38 UTC, nunoarruda commented
@jkasten2 @rgomezp @nan-li @Jeasmine can you folks please take a look at this when you have a chance? It's blocking us (and probably many more teams) from upgrading to v3.x.

Thanks in advance! 🙏

2022-02-11 19:45 UTC, jkasten2 requested changes
@nunoarruda Thanks for the PR! I have reviewed your PR and I have one comment on `undefined` that need to be address before we can merge this in.

2022-02-11 19:45 UTC, jkasten2 commented on types/Notification.d.ts
> +    complete        : (notification: OSNotification | null) => void;
Since we allowed `undefined` we should continue supporting it, so we need to keep the `?` to allow that.

2022-02-11 21:48 UTC, nunoarruda commented on types/Notification.d.ts
> +    complete        : (notification: OSNotification | null) => void;
@jkasten2 ok that makes sense. I've just added the `?`.

2022-02-15 21:34 UTC, nan-li approved these changes
LGTM

2022-02-15 21:34 UTC, merged