Add in app message lifecycle handler
OneSignal/OneSignal-Cordova-SDK pull request #782
Opened 2022-05-08 21:45 UTC by nan-li

# Description
## One Line Summary
Adds the In-App Message Lifecycle Handler which includes up to 4 callbacks for the displaying and dismissing of In-App Messages.

## Details
### Motivation
This handler was added to give customers visibility into the display lifecycle of IAMs: when an IAM will be displayed, and also when it has been dismissed. 

### Scope
- Added the `OSInAppMessage` and `InAppMessageLifecycleHandlerObject` interfaces.
- Add the public function `setInAppMessageLifecycleHandler(InAppMessageLifecycleHandlerObject handlerObject)` which will internally call up to 4 handlers: `setOnWillDisplayInAppMessageHandler`, `setOnDidDisplayInAppMessageHandler`, `setOnWillDismissInAppMessageHandler`, `setOnDidDismissInAppMessageHandler`

### Public API Changes
Yes, the documentation will need to be updated for the Cordova SDK to provide this new method `setInAppMessageLifecycleHandler(InAppMessageLifecycleHandlerObject handlerObject)` and the interfaces `OSInAppMessage` and `InAppMessageLifecycleHandlerObject`

# Testing
## Manual testing
Ran the code in a minimal Cordova example app on Android and iOS emulators.
- [x] Tested setting all 4 callbacks and seeing them triggered in order.
- [x] Tested setting only 2 of the 4 callbacks and seeing them triggered in order, and no other errors appear.
- [x] Tested swiping away the IAM and also clicking on a close button (this led me to find a native iOS issue).

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [x] In-App Messaging
   - [ ] REST API requests
   - [X] Public API changes

# Checklist
## Overview
   - [X] I have filled out all **REQUIRED** sections above
   - [X] PR does one thing
   - [X] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [X] I have included test coverage for these changes, or explained why they are not needed
   - [X] All automated tests pass, or I explained why that is not possible
   - [X] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [X] Code is as readable as possible.
   - [X] I have reviewed this PR myself, ensuring it meets each checklist item

2022-05-16 20:42 UTC, jkasten2 requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/782)* status: all files reviewed, 1 unresolved discussion (waiting on @nan-li, @rgomezp, and @tanaynigam)

___
*[`src/android/com/onesignal/cordova/OneSignalPush.java` line 151 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/782#-N2D_Jiy2QYqAysRR7BE:-N2D_Jiy2QYqAysRR7BF:b-xydiix) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/4df5aa208a4962f24975e2fc0bfc3ee52af0ba84/src/android/com/onesignal/cordova/OneSignalPush.java#L151)):*
> ```Java
>             CallbackHelper.callbackSuccess(jsInAppMessageWillDisplayCallback, message.toJSONObject());
>           }
>         } catch (Throwable t) {
> ```

Should catch specific exception instead of `Throwable` as this can hide root issues.


<!-- Sent from Reviewable.io -->

2022-05-17 02:43 UTC, nan-li reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/782)* status: all files reviewed, 1 unresolved discussion (waiting on @jkasten2, @rgomezp, and @tanaynigam)

___
*[`src/android/com/onesignal/cordova/OneSignalPush.java` line 151 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/782#-N2D_Jiy2QYqAysRR7BE:-N2Eq54S2zRt7RA3amw2:b-ko4npa) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/4df5aa208a4962f24975e2fc0bfc3ee52af0ba84/src/android/com/onesignal/cordova/OneSignalPush.java#L151)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Should catch specific exception instead of `Throwable` as this can hide root issues.
</blockquote></details>

I had thought about this. I can't think of what specific exception it should be catching, but JSONException is taken care of within the method `toJSONObject()` itself. 

I was following the implementation for other callbacks in this file like `notificationWillShowInForeground`, `notificationOpened`, and [`inAppMessageClicked`](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/411c54f37fcb4a4cf4a01ee254da04564b5dc076/src/android/com/onesignal/cordova/OneSignalPush.java#L423-L430), thinking there is some reason for catching Throwables? 

Looking through the git blame, this is not clear, except as leftovers from catching JSON exceptions. I saw when the SDK was created, the JSON exceptions seem to be caught with Throwables such as [here](https://github.com/OneSignal/OneSignal-Cordova-SDK/blame/bec01f04aaa337a053b097f0f8a6f57d3b668725/src/android/com/plugin/gcm/OneSignalPush.java#L94-L101).


<!-- Sent from Reviewable.io -->

2022-05-17 21:46 UTC, jkasten2 requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/782)* status: all files reviewed, 1 unresolved discussion (waiting on @nan-li, @rgomezp, and @tanaynigam)

___
*[`src/android/com/onesignal/cordova/OneSignalPush.java` line 151 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/782#-N2D_Jiy2QYqAysRR7BE:-N2IyGahE5kdFaz4a24-:bqpdufz) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/4df5aa208a4962f24975e2fc0bfc3ee52af0ba84/src/android/com/onesignal/cordova/OneSignalPush.java#L151)):*
<details><summary><i>Previously, nan-li (Nan) wrote…</i></summary><blockquote>

I had thought about this. I can't think of what specific exception it should be catching, but JSONException is taken care of within the method `toJSONObject()` itself. 

I was following the implementation for other callbacks in this file like `notificationWillShowInForeground`, `notificationOpened`, and [`inAppMessageClicked`](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/411c54f37fcb4a4cf4a01ee254da04564b5dc076/src/android/com/onesignal/cordova/OneSignalPush.java#L423-L430), thinking there is some reason for catching Throwables? 

Looking through the git blame, this is not clear, except as leftovers from catching JSON exceptions. I saw when the SDK was created, the JSON exceptions seem to be caught with Throwables such as [here](https://github.com/OneSignal/OneSignal-Cordova-SDK/blame/bec01f04aaa337a053b097f0f8a6f57d3b668725/src/android/com/plugin/gcm/OneSignalPush.java#L94-L101).
</blockquote></details>

ah ya seems you are right and we don't need to catch anything at all here.

Historically we have had to catch a lot of JSON exceptions in this file, and we have been using using `Throwable` for them. However we should have been using `JsonException`.


<!-- Sent from Reviewable.io -->

2022-05-17 23:19 UTC, nan-li reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/782)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @jkasten2, @rgomezp, and @tanaynigam)

___
*[`src/android/com/onesignal/cordova/OneSignalPush.java` line 151 at r1](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/782#-N2D_Jiy2QYqAysRR7BE:-N2JJEEf1c74WMtsibTQ:b-l5souq) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/4df5aa208a4962f24975e2fc0bfc3ee52af0ba84/src/android/com/onesignal/cordova/OneSignalPush.java#L151)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

ah ya seems you are right and we don't need to catch anything at all here.

Historically we have had to catch a lot of JSON exceptions in this file, and we have been using using `Throwable` for them. However we should have been using `JsonException`.
</blockquote></details>

Done. Added a commit to remove try-catch and include some information.


<!-- Sent from Reviewable.io -->

2022-05-17 23:20 UTC, jkasten2 approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/782)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rgomezp and @tanaynigam)



<!-- Sent from Reviewable.io -->

2022-05-17 23:20 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/782#-:-N2JJacn5hk5u78OwXmN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rgomezp and @tanaynigam)



<!-- Sent from Reviewable.io -->

2022-05-17 23:34 UTC, merged