WiP to view how commit changes look
OneSignal/OneSignal-Cordova-SDK pull request #798
Opened 2022-06-28 02:50 UTC by nan-li

# READ AND DELETE THIS SECTION BEFORE SUBMITTING PR
* **Fill out each _REQUIRED_ section**
* **Fill out _OPTIONAL_ sections, remove section if it doesn't apply to your PR**
* **Read and fill out each of the checklists below**
* **Remove this section after reading**

# Description
## One Line Summary
**REQUIRED** - Very short description that summaries the changes in this PR.

## Details

### Motivation
**REQUIRED -** Why is this code change being made? Or what is the goal of this PR? Examples: Fixes a specific bug, provides additional logging to debug future issues, feature to allow X.

### Scope
**RECOMMEND - OPTIONAL -** What is intended to be effected. What is known not to change. Example: Notifications are grouped when parameter X is set, not enabled by default.

### OPTIONAL - Other
**OPTIONAL -** Feel free to add any other sections or sub-sections that can explain your PR better.

# Testing
## Unit testing
**OPTIONAL -**  Explain unit tests added, if not clear in the code.

## Manual testing
**RECOMMEND - OPTIONAL -** Explain what scenarios were tested and the environment.
Example: Tested opening a notification while the app was foregrounded, app build with Android Studio 2020.3 with a fresh install of the OneSignal example app on a Pixel 6 with Android 12.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [ ] I have filled out all **REQUIRED** sections above
   - [ ] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [ ] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [ ] I have included test coverage for these changes, or explained why they are not needed
   - [ ] All automated tests pass, or I explained why that is not possible
   - [ ] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [ ] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [ ] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2022-06-30 21:48 UTC, rgomezp commented on src/android/com/onesignal/cordova/OneSignalPush.java
> +        actionJSON.put("clickUrl", resultJSON.optString("click_url", null));
Why do you say the types are incorrect? If you are converting to camelCase, then it is snake case currently which is consistent with RN. We have used snake case for quite a while.

We can convert to camel case, but this is a breaking change so we would need to make a major release.

2022-06-30 23:14 UTC, rgomezp requested changes

2022-06-30 23:14 UTC, rgomezp commented on www/index.ts
> +    const internalCallback = (data: any) => {
make a new type. avoid using any

2022-07-01 00:23 UTC, jkasten2 requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/798)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @emawby and @nan-li)

___
*[`package.json` line 12 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/798#-N5r7WXb4vLtrNAXc6DM:-N5r7WXb4vLtrNAXc6DN:br4p0ru) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/c05ad8dcfce440ebea1d33d6978db42566f60418/package.json#L12)):*
> ```JSON
>   "scripts": {
>     "prepare": "npm run build",
>     "build": "tsc"
> ```

Does this introduce any new requirements? Do they need to install `tsc` or does that come with Cordova and Ionic?


<!-- Sent from Reviewable.io -->

2022-07-01 00:27 UTC, nan-li commented on src/ios/OneSignalPush.m
> +    [OneSignal postNotificationWithJsonString:command.arguments[0]
This is a good call. We do need to revisit this because currently, although the public interface is a string, it would not have worked if a user passes a string, there would be errors.

2022-07-01 00:42 UTC, nan-li commented on package.json
> +    "prepare": "npm run build",
Maybe use `yarn` instead. And commit a lock file?

2022-07-01 00:45 UTC, jkasten2 requested changes
> Reviewed 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/798)* status: 1 of 24 files reviewed, 1 unresolved discussion (waiting on @emawby and @nan-li)

___
*[`package.json` line 12 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/798#-N5r7WXb4vLtrNAXc6DM:-N5rCq3m0AsuLGgQUJu_:bgns6gy) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/c05ad8dcfce440ebea1d33d6978db42566f60418/package.json#L12)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Does this introduce any new requirements? Do they need to install `tsc` or does that come with Cordova and Ionic?
</blockquote></details>

Or is the run when we ship an release? Therefore the ts.d file and .js files are what is actually published?


<!-- Sent from Reviewable.io -->

2022-07-01 00:55 UTC, nan-li reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/798)* status: 1 of 24 files reviewed, 1 unresolved discussion (waiting on @emawby and @jkasten2)

___
*[`package.json` line 12 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/798#-N5r7WXb4vLtrNAXc6DM:-N5rCopqCY7Lfj5EPuTI:bom8upl) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/c05ad8dcfce440ebea1d33d6978db42566f60418/package.json#L12)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Or is the run when we ship an release? Therefore the ts.d file and .js files are what is actually published?
</blockquote></details>

Yup, this is run before we publish and users will rely on the generated `.js` and `d.ts` files that will be generated under a new folder called `dist`


<!-- Sent from Reviewable.io -->

2022-07-05 18:06 UTC, nan-li commented on www/index.ts
> +    const internalCallback = (data: any) => {
I added a commit to pass the boolean from the iOS bridge so we don't have to extract. I did this for some other iOS bridge methods that corrected the callback received by the user. The commit has more details.

2022-07-05 18:29 UTC, nan-li commented on www/Subscription.ts
> +        // rename the subscrbied properties to align with existing type definition
fixed

2022-07-05 18:29 UTC, nan-li commented on src/ios/OneSignalPush.m
> +    [OneSignal postNotificationWithJsonString:command.arguments[0]
Added commit to update interface to `object`

2022-07-05 18:29 UTC, nan-li commented on www/index.ts
> +        for (let i = 0; i < array.length; i++)
Fixed brackets in nit commit

2022-07-05 21:42 UTC, nan-li commented
Summarizing the changes I added since last review are:
- Updated package.json to use `yarn` instead of `npm`. The lockfile generated is actually empty because the SDK names no dependencies, so no lockfile is committed.
- Add `outcomes` and `tags` to `InAppMessageAction` and tested this via the IAM click handler on iPhone and Android when these are present and when these are not.
- Update how iOS passes booleans to the JavaScript code and users' callbacks. Now, several methods will pass the boolean directly instead of as an object such as `{accepted: true}`. Android has always been passing the boolean, so now both platforms are consistent. This also fixes type inconsistencies as the public interface declares that users will receive a boolean as a callback response, but we had previously been passing them an object on iOS and a boolean on Android.
- Correct the `postNotification` interface to take `object` instead of `string` (which was erroneous).
- A nit commit to remove some trailing white space, spaces, add brackets to JavaScript code, and add two comments.

2022-07-05 22:56 UTC, jkasten2 requested changes
> Reviewed 4 of 20 files at r1, 3 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/798)* status: 7 of 24 files reviewed, 3 unresolved discussions (waiting on @emawby, @jkasten2, @nan-li, and @rgomezp)

___
*[`package.json` line 12 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/798#-N5r7WXb4vLtrNAXc6DM:-N6FVegGCXQ1sRxWbFEi:b-ksemp2) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/c05ad8dcfce440ebea1d33d6978db42566f60418/package.json#L12)):*
<details><summary><i>Previously, nan-li (Nan) wrote…</i></summary><blockquote>

Yup, this is run before we publish and users will rely on the generated `.js` and `d.ts` files that will be generated under a new folder called `dist`
</blockquote></details>

ah ok, would be good to include this in the PR details.
___
*[`www/index.ts` line 94 at r3](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/798#-N6FXE8REKzzYmkOdWMC:-N6FXE8REKzzYmkOdWMD:bqzhbvn) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/48994c9718641a0c53c904de4c8bb210c6071392/www/index.ts#L94)):*
> ```XML
>         const foregroundParsingHandler = (notificationReceived: OSNotification) => {
> 
>             console.log("foregroundParsingHandler " + JSON.stringify(notificationReceived));
> ```

Log entry should removed or should start with OneSignal so the source of it is known.
___
*[`www/index.ts` line 587 at r3](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/798#-N6FZVVE9Nt9YUrG58zo:-N6FZVVE9Nt9YUrG58zp:bz1nuf8) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/48994c9718641a0c53c904de4c8bb210c6071392/www/index.ts#L587)):*
> ```XML
>         }
> 
>         var passToNativeParams = [externalId];
> ```

Could be `const`


<!-- Sent from Reviewable.io -->

2022-07-08 20:56 UTC, rgomezp approved these changes

2022-07-08 20:56 UTC, rgomezp commented on package.json
> +    "build": "tsc"
Not a blocker, but would be nice to add ESLint as a prebuild step:

`"prepare": "yarn run lint && yarn run build"`
`"lint": "eslint . --ext .ts"`

2022-07-12 18:48 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 20 files at r1, 5 of 12 files at r2, 5 of 5 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/798#-:-N6njL-d2QhpaKRP1rds:bnfp4nl)* status: 23 of 24 files reviewed, all discussions resolved (waiting on @emawby and @jkasten2)



<!-- Sent from Reviewable.io -->

2022-07-20 01:02 UTC, nan-li commented on package.json
> +    "build": "tsc"
Good idea, let's follow up on this later since we need to make the configuration, and it can also be applied to `react-native-onesignal` which doesn't have a linter also.

2022-07-21 21:06 UTC, nan-li commented
Added 2 commits to the PR. 
- The first caught 2 issues while I was combing through the PR changes. 
- The second reverts https://github.com/OneSignal/OneSignal-Cordova-SDK/pull/798/commits/3eb8ad71d499dcf4e318e63d2f1f8cf003197b04 and keeps iOS boolean callbacks the same, and updates the interface.

I also added a section called **Summary of Public Interface Changes** to the PR description that lists all the public-facing changes of this PR, making it easier to see at a glance everything that changed.

2022-07-23 00:14 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/798#-:-N7cOqUZ60nFMMgCol0P:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @emawby and @rgomezp)



<!-- Sent from Reviewable.io -->

2022-07-26 22:16 UTC, merged