Update Debug methods
OneSignal/OneSignal-Cordova-SDK pull request #855
Opened 2023-02-02 10:40 UTC by jennantilla

# Description
## One Line Summary
Update Debug methods to handle logging on Android.

## Details

### Motivation
Add/Rename methods to conform to User Model conventions.

### Scope
Logging methods will be invoked as:
```
window.plugins.OneSignal.Debug.setLogLevel(6);
window.plugins.OneSignal.Debug.setAlertLevel(0);
```

### OPTIONAL - Other
This PR only encompasses changes to Android. Changes to the main plugin interface and iOS were submitted in a previous PR: https://github.com/OneSignal/OneSignal-Cordova-SDK/pull/846

# Testing
## Unit testing
No unit testing was used

## Manual testing
**RECOMMEND - OPTIONAL -** Explain what scenarios were tested and the environment.
Tested logging methods on a Samsung S21 device running Android 13.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [X] Public API changes

# Checklist
## Overview
   - [X] I have filled out all **REQUIRED** sections above
   - [X] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [X] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [X] I have included test coverage for these changes, or explained why they are not needed
   - [X] All automated tests pass, or I explained why that is not possible
   - [X] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [X] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [X] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2023-02-03 15:24 UTC, brismithers requested changes

2023-02-03 15:24 UTC, brismithers commented on src/android/com/onesignal/cordova/OneSignalController.java
> +      OneSignal.getDebug().setLogLevel(visuallevel);
this should be `OneSignal.getDebut().setAlertLevel(visualLevel)`

2023-02-07 00:51 UTC, jennantilla commented on src/android/com/onesignal/cordova/OneSignalController.java
> +      OneSignal.getDebug().setLogLevel(visuallevel);
Ooops, typo! Now fixed below

2023-02-07 22:15 UTC, brismithers approved these changes

2023-02-08 06:24 UTC, merged