OneSignal Class Updates
OneSignal/OneSignal-Cordova-SDK pull request #856
Opened 2023-02-03 10:27 UTC by jennantilla

# Description
## One Line Summary
Update methods that are not namespaced and will remain within the OneSignal class.

## Details

### Motivation
Some methods are to remain on the main OneSignal class, with some updates.

### Scope
Methods to remain on the OneSignal class will be invoked as:
`window.plugins.OneSignal.login("externalId")`;
`window.plugins.OneSignal.logout()`;
` window.plugins.OneSignal.setPrivacyConsent(true);`
`window.plugins.OneSignal.getPrivacyConsent((getPrivacyConsent) => {});`
`window.plugins.OneSignal.setRequiresPrivacyConsent(true);`
`window.plugins.OneSignal.getRequiresPrivacyConsent((getRequiresPrivacyConsent) => {});`
`

### OPTIONAL - Other
This PR encompasses the changes to both Android and iOS, in different commits.

# Testing
## Unit testing
No unit testing was used.

## Manual testing
Tested these methods on an iPad running iOS 15.2 and Samsung Galaxy S21 running Android 13.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [X] Public API changes

# Checklist
## Overview
   - [X] I have filled out all **REQUIRED** sections above
   - [X] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [X] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [X] I have included test coverage for these changes, or explained why they are not needed
   - [X] All automated tests pass, or I explained why that is not possible
   - [X] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [X] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [X] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2023-02-03 15:30 UTC, brismithers commented on www/index.ts
> +    login(externalId: string): void {
note there will be a `jwtBearerToken` optional parameter here at some point.

2023-02-03 15:30 UTC, brismithers approved these changes

2023-02-03 19:22 UTC, jkasten2 requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-Cordova-SDK/856)* status: all files reviewed, 6 unresolved discussions (waiting on @emawby, @fhboswell, @jennantilla, and @nan-li)

___
*[`src/android/com/onesignal/cordova/OneSignalController.java` line 71 at r1](https://reviewable.io/reviews/OneSignal/OneSignal-Cordova-SDK/856#-NNNhCPV9JkwQtix6POE:-NNNhCPV9JkwQtix6POF:b-77e9me) ([raw file](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/73020e50bd5679294527bc717e7048e95f36499c/src/android/com/onesignal/cordova/OneSignalController.java#L71)):*
> ```Java
>       return true;
>     }
>     catch (Throwable t) {
> ```

Recommend we catch the specific exception, `JSONException` in this case. This way we don't eat other errors and move on, they lead to unpredictable state which results in misleading and hard to debug issues.
___
*[`src/android/com/onesignal/cordova/OneSignalController.java` line 78 at r1](https://reviewable.io/reviews/OneSignal/OneSignal-Cordova-SDK/856#-NNNhxOECCg7rhAf4QTr:-NNNhxOECCg7rhAf4QTs:b-cs4xln) ([raw file](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/73020e50bd5679294527bc717e7048e95f36499c/src/android/com/onesignal/cordova/OneSignalController.java#L78)):*
> ```Java
> 
>   public static boolean logout() {
>     try {
> ```

`OneSignal.logout();` doesn't throw so we can remove the try-catch.



_Code quote:_
```Java
OneSignal.logout();
```
___
*[`src/android/com/onesignal/cordova/OneSignalController.java` line 339 at r1](https://reviewable.io/reviews/OneSignal/OneSignal-Cordova-SDK/856#-NNNiB81A7hDa3lge_OU:-NNNiB821Vm5gjFWbRGH:bvikmxg) ([raw file](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/73020e50bd5679294527bc717e7048e95f36499c/src/android/com/onesignal/cordova/OneSignalController.java#L339)):*
> ```Java
>   public static boolean enterLiveActivity() {
>   // doesn't apply to Android
>   return true;
> ```

nit, missing indenting
___
*[`src/android/com/onesignal/cordova/OneSignalController.java` line 343 at r1](https://reviewable.io/reviews/OneSignal/OneSignal-Cordova-SDK/856#-NNNiEi70OVZDtTc_oHm:-NNNiEi70OVZDtTc_oHn:bvikmxg) ([raw file](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/73020e50bd5679294527bc717e7048e95f36499c/src/android/com/onesignal/cordova/OneSignalController.java#L343)):*
> ```Java
> 
>   public static boolean exitLiveActivity() {
>   // doesn't apply to Android
> ```

nit, missing indenting
___
*[`src/android/com/onesignal/cordova/OneSignalPush.java` line 423 at r1](https://reviewable.io/reviews/OneSignal/OneSignal-Cordova-SDK/856#-NNNiPSL5yFrt2hCt9_O:-NNNiPSL5yFrt2hCt9_P:b8b1vfp) ([raw file](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/73020e50bd5679294527bc717e7048e95f36499c/src/android/com/onesignal/cordova/OneSignalPush.java#L423)):*
> ```Java
> 
>       case ENTER_LIVE_ACTIVITY:
>       result = OneSignalController.enterLiveActivity();
> ```

nit, consistent indenting with other case statements in this file.


<!-- Sent from Reviewable.io -->

2023-02-03 23:44 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-Cordova-SDK/856#-:-NNOed5JCkR6K1dCPVlo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @emawby, @fhboswell, @jennantilla, and @nan-li)



<!-- Sent from Reviewable.io -->

2023-02-04 00:24 UTC, fhboswell approved these changes

2023-02-04 00:32 UTC, merged