[User Model] Update PushSubscription methods on Android
OneSignal/OneSignal-Cordova-SDK pull request #859
Opened 2023-02-08 06:22 UTC by jennantilla

# Description
## One Line Summary
Update PushSubscription methods on Android

## Details

### Motivation
Update methods to adhere to User Model conventions.

### Scope
PushSubscription has updated methods to observe and access push subscription behavior/properties. They will be invoked as:
`window.plugins.OneSignal.User.pushSubscription.addObserver(function (state){...});`
`window.plugins.OneSignal.User.pushSubscription.removeObserver();`
`window.plugins.OneSignal.User.pushSubscription.optIn();`
`window.plugins.OneSignal.User.pushSubscription.optOut();`

Separate internal methods were created in order to access pushSubscription properties with the following API:
`let pushId = window.plugins.OneSignal.User.pushSubscription.id;`
`let token = window.plugins.OneSignal.User.pushSubscription.token;`
`let optedIn = window.plugins.OneSignal.User.pushSubscription.optedIn;`

### OPTIONAL - Other
This PR only encompasses changes to Android and some small updates to the main plugin/iOS files. Previous iOS PR here: https://github.com/OneSignal/OneSignal-Cordova-SDK/pull/852

# Testing
## Unit testing
No unit testing was used.

## Manual testing
**RECOMMEND - OPTIONAL -** Explain what scenarios were tested and the environment.
Successfully tested methods on Samsung Galaxy S21 running Android 13 and various emulators running Android 12 and Android 13.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [X] Public API changes

# Checklist
## Overview
   - [X] I have filled out all **REQUIRED** sections above
   - [X] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [X] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [X] I have included test coverage for these changes, or explained why they are not needed
   - [X] All automated tests pass, or I explained why that is not possible
   - [X] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [X] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [X] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2023-02-09 03:18 UTC, jennantilla commented
@nan-li heads up I incorporated your [previous suggestions](https://github.com/OneSignal/OneSignal-Cordova-SDK/pull/852#pullrequestreview-1283592647) from https://github.com/OneSignal/OneSignal-Cordova-SDK/pull/852 in [Update removeObserver method and iOS implementation](https://github.com/OneSignal/OneSignal-Cordova-SDK/pull/859/commits/5a7eb2834f9519a54dd24857558405b3a8dedb30)

2023-02-13 18:19 UTC, brismithers approved these changes

2023-02-13 18:19 UTC, brismithers commented on src/android/com/onesignal/cordova/OneSignalController.java
> +  public static boolean optIn() {
I'm wondering if we should be more verbose with what these functions represent, something like `optInPushSubscription`, `getPushSubscriptionId`, etc.  Or maybe put these in a `OneSignalPushSubscriptionController` class dedicated to the push subscription methods.  Thoughts?

2023-02-14 00:24 UTC, jennantilla commented on src/android/com/onesignal/cordova/OneSignalController.java
> +  public static boolean optIn() {
Makes sense! I've adjusted the method names for now and will look into separating out in to classes post-beta1.

2023-02-14 16:48 UTC, nan-li requested changes
You are making great PRs and each commit is very clear and easy to follow. We can look at these comments in our 1:1 today

2023-02-14 16:48 UTC, nan-li commented on src/android/com/onesignal/cordova/OneSignalObserverController.java
> +  private static ISubscriptionChangedHandler handler;
I recommend renaming `handler` to something more specific like `subscriptionChangedHandler` because we can have other handlers as well.

2023-02-14 16:48 UTC, nan-li commented on src/android/com/onesignal/cordova/OneSignalObserverController.java
> +  public static boolean removePushSubscriptionObserver() {
I think the way we set up our Cordova SDK, this method `removePushSubscriptionObserver` would never be called, it can be removed.

2023-02-14 16:48 UTC, nan-li commented on src/android/com/onesignal/cordova/OneSignalObserverController.java
> +      handler = new ISubscriptionChangedHandler() {
set the `handler` to a new one only if it hasn't already been. See the similar implementation on `main` that checks this. This is just like that `if (first)` check on iOS side. https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/2e7b99246f47ea91c4905a2e8fa157c7c354c7bd/src/android/com/onesignal/cordova/OneSignalObserverController.java#L91

2023-02-14 16:48 UTC, nan-li commented on src/ios/OneSignalPush.m
>      successCallback(subscriptionObserverCallbackId, [stateChanges toDictionary]);
This method has been renamed to `(void)onOSPushSubscriptionChangedWithStateChanges:(OSPushSubscriptionStateChanges *)stateChanges`. Does this still work and fire the push sub observer?

2023-02-14 16:48 UTC, nan-li commented on src/android/com/onesignal/cordova/OneSignalObserverController.java
> +            pushSubscriptionProperties.put("id", pushSubscription.getId());
I realized that the objects passed are different on iOS and Android. Would need to test if it works or how to remedy it. `pushSubscriptionProperties` would passed over the bridge by Android would be like:
```json
{ 
  "token": "someToken",
  "optedIn": true,
  "id": "someId"
}
```
Where as for iOS, it has this shape
```json
{ 
    "from": {
        "token": "someToken",
        "optedIn": true,
        "id": "someId"
    },
    "to": {
        "token": "someToken",
        "optedIn": true,
        "id": "someId"
    }
}
```
Maybe we format the iOS side to pass only the `"to"` portion so that it matches Android.

2023-02-14 22:53 UTC, jennantilla commented on src/ios/OneSignalPush.m
>      successCallback(subscriptionObserverCallbackId, [stateChanges toDictionary]);
This will be in a follow-up PR, will be sure to confirm that this works once merged.

2023-02-15 00:01 UTC, nan-li approved these changes
Great work~

2023-02-15 20:28 UTC, merged