[User Model] Notifications namespace and implementations for iOS & Android
OneSignal/OneSignal-Cordova-SDK pull request #863
Opened 2023-02-09 22:09 UTC by jennantilla

# Description
## One Line Summary
Create Notifications namespace and implementations for iOS & Android.

## Details

### Motivation
Create Notifications namespace to decouple from OneSignal class to adhere to User Model conventions.

### Scope
Updates included for both iOS and Android.

Methods will be invoked as:
`window.plugins.OneSignal.Notifications.setNotificationOpenedHandler(function(opened) {...});`
`window.plugins.OneSignal.Notifications.setNotificationWillShowInForegroundHandler(function(willShow) {...});`
`window.plugins.OneSignal.Notifications.addPermissionObserver();`
`window.plugins.OneSignal.Notifications.removePermissionObserver();`
`window.plugins.OneSignal.Notifications.requestPermission();`
`window.plugins.OneSignal.Notifications.clearAll();`

iOS Only:
`window.plugins.OneSignal.Notifications.registerForProvisionalAuthorization();`
`window.plugins.OneSignal.Notifications.canRequestPermission(function (canRequest) {...});`

Android Only:
`window.plugins.OneSignal.Notifications.removeNotification();`
`window.plugins.OneSignal.Notifications.removeGroupedNotifications();`

Internal methods `_setPropertyAndObserver()` and `getPermission()` were created to allow developers to access permission status with:
`let permission = window.plugins.OneSignal.Notifications.permission`

### OPTIONAL - Other
**OPTIONAL -** Feel free to add any other sections or sub-sections that can explain your PR better.

# Testing
## Unit testing
No unit testing was used.

## Manual testing
**RECOMMEND - OPTIONAL -** Explain what scenarios were tested and the environment.
Tested methods on Samsung Galaxy S21 running Android 13 and 6th Gen iPad running iOS 15.2.

# Affected code checklist
   - [X] Notifications
      - [X] Display
      - [X] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [X] Public API changes

# Checklist
## Overview
   - [X] I have filled out all **REQUIRED** sections above
   - [X] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [X] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [X] I have included test coverage for these changes, or explained why they are not needed
   - [X] All automated tests pass, or I explained why that is not possible
   - [X] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [X] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [X] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2023-02-09 22:14 UTC, jennantilla commented on src/android/com/onesignal/cordova/OneSignalPush.java
> +        // foregroundData.put("rawPayload", notification.getrawPayload());
@brismithers - one question here:

I can't access `rawPayload`. Error is `cannot find symbol`. Is it because [`rawPayload`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/9fc1c61094fae6b36feb81ddcb55e6a5ed26af40/OneSignalSDK/onesignal/notifications/src/main/java/com/onesignal/notifications/internal/Notification.kt#L54) is not `override var`?

2023-02-16 00:00 UTC, nan-li requested changes
Looks Great! A few small things. I think some of these you may already planned for an future PR

2023-02-16 01:24 UTC, jennantilla commented on src/android/com/onesignal/cordova/OneSignalPush.java
> +        foregroundData.put("sound", notification.getSound());
yeah, the toJSONObject method didn't work with a few of the changes!

2023-02-17 20:26 UTC, nan-li approved these changes

2023-02-17 20:37 UTC, merged