[User Model] Update In-App Messages API
OneSignal/OneSignal-Cordova-SDK pull request #886
Opened 2023-05-12 08:35 UTC by jennantilla

# Description
## One Line Summary
Update In-App Messages API.

## Details

addTriggers API Update
1. addTrigger and addTriggers will only accept string values, not types string/bool/number, etc.

IAM Lifecycle Listener Updates
1. Change naming of methods from `set` to `add`
2. Native methods updated to receive specific event types (e.g., InAppMessageDidDisplayEvent)
3. Update of Cordova InAppMessage interfaces and events types
4. Add removeLifecycleListener method

IAM Click Listener
1. Change naming of methods from `set` to `add`
2. Support adding and removing multiple click listeners
4. Add a remove method for the click listener
5. Replace OSInAppMessageAction with OSInAppMessageClickResult
6. OSInAppMessageClickEvent passed to developers instead of OSInAppMessageAction

### Scope
Changes limited to InAppMessages namespace. 

# Testing

## Manual testing
Tested running plugin on both Samsung Galaxy S21 and various Android emulators all running Android 13. Tested running plugin on 6th gen iPad running 15.2 and later upgraded to 16.4.1.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [X] In-App Messaging
   - [ ] REST API requests
   - [X] Public API changes

# Checklist
## Overview
   - [X] I have filled out all **REQUIRED** sections above
   - [X] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [X] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [X] I have included test coverage for these changes, or explained why they are not needed
   - [X] All automated tests pass, or I explained why that is not possible
   - [X] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [X] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [X] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2023-05-16 06:55 UTC, jennantilla commented
@jkasten2  I think my [latest commit](https://github.com/OneSignal/OneSignal-Cordova-SDK/pull/886/commits/1f7b1529561b7393ce6cd10558c17176087b1a40) is getting us close to where we need to be with addEvent Listener.

It currently works but I doubt this is completely right because as-is, the event listeners will get added multiple times.

I think the issue is where I’m calling the native [addInAppMessageLifecycleListener](https://github.com/OneSignal/OneSignal-Cordova-SDK/pull/886/commits/1f7b1529561b7393ce6cd10558c17176087b1a40#diff-af87b430f6a0b796985892b3f6ee8947ac133bf8e134a05e06a2dcfadaa55079R69) / [addInAppMessageClickListener](https://github.com/OneSignal/OneSignal-Cordova-SDK/pull/886/commits/1f7b1529561b7393ce6cd10558c17176087b1a40#diff-af87b430f6a0b796985892b3f6ee8947ac133bf8e134a05e06a2dcfadaa55079R39) in Cordova, but I’m at a bit of a loss about the best way to refactor.

Any suggestions appreciated!

2023-05-16 15:56 UTC, jkasten2 requested changes

2023-05-16 15:56 UTC, jkasten2 commented on src/ios/OneSignalPush.m
> +    bool first = addInAppMessageClickListenerCallbackId = command.callbackId;
The assignment on this line will make all 3 variables the same value, that doesn't look to be the intent here. Did you mean to check if the id values match instead? Even in that case though the callbackId value will be different every time so `first` would always be true. Checking if `addInAppMessageClickListenerCallbackId` is `nil` would work here.

However instead of doing this first check here, and having to code that for Android as well, I would recommend doing the check at the Typescript level so you only need to code and test this once.

2023-05-18 22:13 UTC, jennantilla commented on src/ios/OneSignalPush.m
> +    bool first = addInAppMessageClickListenerCallbackId = command.callbackId;
Per discussion with Elliot, the listeners are now added on init in the native bridges and no longer called from Cordova, so I think we can omit this check?

2023-05-18 22:53 UTC, jennantilla commented
@jkasten2 @emawby @nan-li @shepherd-l - Ok I believe this PR should be ready for final review! Tested that click and lifecycle listeners are added and logged correctly. Will also update migration guide and V11 documentation to use these public APIs:

`OneSignal.InAppMessages.addEventListener("willDisplay", function(event) {});`
`OneSignal.InAppMessages.addEventListener("didDisplay", function(event) {});`
`OneSignal.InAppMessages.addEventListener("willDismiss", function(event) {});`
`OneSignal.InAppMessages.addEventListener("didDismiss", function(event) {});`
`OneSignal.InAppMessages.addEventListener("click", function(event) {});`

2023-05-22 15:54 UTC, emawby approved these changes

2023-05-22 18:33 UTC, jkasten2 approved these changes
Some extra fields on iOS that should be cleaned up, but otherwise this PR looks good for the IAM changes

2023-05-22 18:33 UTC, jkasten2 commented on src/ios/OneSignalPush.m
> +        @"outcomes" : eventDict[@"outcomes"] ?: [NSNull null],
Remove `outomes` and `tags` from iOS. We decided to omit this since were only useful for debugging.

2023-06-02 19:59 UTC, jkasten2 approved these changes

2023-06-02 20:15 UTC, merged