[User Model] Update Migration Guide
OneSignal/OneSignal-Cordova-SDK pull request #888
Opened 2023-05-12 18:06 UTC by jennantilla

# Description
## One Line Summary
Update Migration Guide for latest beta release.

## Details

### Motivation
Keep documentation synchronized with code updates.

### Scope
Included updates to InAppMessages, Notifications, pushSubscription, permission, privacy, and LiveActivities

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [X] Public API changes

# Checklist
## Overview
   - [X] I have filled out all **REQUIRED** sections above
   - [X] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [X] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [X] I have included test coverage for these changes, or explained why they are not needed
   - [X] All automated tests pass, or I explained why that is not possible
   - [X] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [X] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [X] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2023-05-12 20:30 UTC, emawby requested changes

2023-05-12 20:30 UTC, emawby commented on MIGRATION_GUIDE.md
> +| ` window.plugins.OneSignal.InAppMessages.addLifecycleListener(listenerObject);`<br><br>***See below for usage*** | *Set the in-app message lifecycle listener.*
We will need to update this to reflect having individual methods once the IAM pr is fixed as well

2023-05-25 21:17 UTC, jkasten2 approved these changes

2023-05-25 21:17 UTC, jkasten2 commented on MIGRATION_GUIDE.md
> +          event.notification.display();
nit, whitespace is off here.

2023-06-02 19:58 UTC, jkasten2 approved these changes

2023-06-02 20:13 UTC, merged